version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: luvinco-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    networks:
      - luv_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=luvinco
      - DB_USERNAME=root
      - DB_PASSWORD=root

  mysql:
    image: mysql:8.0
    container_name: luvinco-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: luvinco
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - luv_net

  nginx:
    image: nginx:alpine
    container_name: luvinco-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - luv_net

volumes:
  mysql_data:

networks:
  luv_net:
    driver: bridge
